sudo: required

os:
  - linux

language: c

services:
  - docker

before_install:
  - docker pull ubuntu:16.04
  - docker pull microsoft/mssql-server-linux:2017-latest

script:
  - docker run --net=host -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Passw0rd' -d microsoft/mssql-server-linux:2017-latest
  - echo "Running docker for commit $TRAVIS_COMMIT"
  - docker build . --tag stack-test
  - docker run --net=host -e "ODBC_TEST_CONNECTION_STRING=\"DRIVER=ODBC Driver 17 for SQL Server;SERVER=127.0.0.1;Uid=SA;Pwd=Passw0rd\"" -w /odbc stack-test:latest sh test/docker-build
