sudo: required

os:
  - linux

language: c

services:
  - docker

before_install:
  # Linux
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then docker pull ubuntu:16.04; fi

script:
  # Both Linux and OS X
  - docker run --net=host -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Passw0rd' -d microsoft/mssql-server-linux:2017-latest
  # Linux
  - echo "Running docker for commit $TRAVIS_COMMIT"
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then docker build --build-arg travis_commit=$TRAVIS_COMMIT . --tag stack-test && docker run --net=host -e "ODBC_TEST_CONNECTION_STRING='DRIVER={ODBC Driver 13 for SQL Server};SERVER=127.0.0.1;Uid=SA;Pwd=Passw0rd'" -w /odbc stack-test:latest stack test; fi
